### ISSUE TITLE
Whatapp will not start, claims Chrome Browser 36+ is required

### ISSUE THREAD

**Issue by arlenn** [meetfranz/franz#1138]
Expected Behavior
Whatsapp should work
Identical to closed issue #1115, https://github.com/meetfranz/franz/issues/1115

Current Behavior
When trying to access whatsapp the following message appears:

WhatsApp works with Google Chrome 36+
To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.

Possible Solution
Remove and Re-add service, DOES NOT WORK!

Steps to Reproduce (for bugs)
Setup a Whatsapp account in Franz

Your Environment
Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / Windows / x64

Operating System and version: Windows 10 - 1803

**Comment by awreccan** [comment]
+1 for MacOS High Sierra 10.13.6

**Comment by riaanvddool** [comment]
+1 for Ubuntu Bionic

**Comment by Cookiezzz** [comment]
I had the same issue this morning on 
Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / Windows / x64
Operating System and version: Windows 10 - 1803

However, I deleted all my services and added them again.
Now it seems to be working for me again.

**Comment by RyukSniper** [comment]
+1 for Windows Insider Preview 18290

**Comment by SDVII** [comment]
+1 Same here, Ubuntu 18.04 LTS

**Comment by SDVII** [comment]
> I had the same issue this morning on
> Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / Windows / x64
> Operating System and version: Windows 10 - 1803
> 
> However, I deleted all my services and added them again.
> Now it seems to be working for me again.

Doesn't seem to work

**Comment by ubk77** [comment]
> I had the same issue this morning on
> Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / Windows / x64
> Operating System and version: Windows 10 - 1803
> 
> However, I deleted all my services and added them again.
> Now it seems to be working for me again.

It works for me. Thanks!

**Comment by bangpius** [comment]
Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / Windows / x86
Operating System and version: Windows 10 

me its okay... like this >> http://prntscr.com/low8a9

**Comment by dinz1** [comment]
> > However, I deleted all my services and added them again.
> > Now it seems to be working for me again.
> 
> Doesn't seem to work

Same here, either not working at all or only for a short time. MacOS 10.14.1.

**Comment by akeijzer11** [comment]
same issue on:
Windows 10 Insider Preview 18290.1000 (rs_prerelease)
using Chrome 70.0.3538.110 (64-bits)
Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / Win32 / x64

however if i click on ''toggle SERVICE D..'' and click on release notes I see chrome version 59
![image](https://user-images.githubusercontent.com/25773759/49284079-c6f33e80-f493-11e8-8157-ee0c4e2fe5ac.png)

if i click on ''toggle Developer tools'' the release notes functions are not available

**Comment by RyukSniper** [comment]
I resolve whit this ty!
> I had the same issue this morning on
> Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / Windows / x64
> Operating System and version: Windows 10 - 1803
> 
> However, I deleted all my services and added them again.
> Now it seems to be working for me again.
> 
> UPDATE: Restarted Franz. WhatsApp broken again and removing services does nothing this time.

**Comment by tcelestino** [comment]
> I had the same issue this morning on
> Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / Windows / x64
> Operating System and version: Windows 10 - 1803
> 
> However, I deleted all my services and added them again.
> Now it seems to be working for me again.
> 
> UPDATE: Restarted Franz. WhatsApp broken again and removing services does nothing this time.

I tried here but the problem carry on. 😞

**Comment by iandoug** [comment]
Clicking the Firefox link opens Firefox on the Download Firefox page .... go figure. Running Linux.

**Comment by dennisvandenende** [comment]
> I had the same issue this morning on
> Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / Windows / x64
> Operating System and version: Windows 10 - 1803
> 
> However, I deleted all my services and added them again.
> Now it seems to be working for me again.
> 
> UPDATE: Restarted Franz. WhatsApp broken again and removing services does nothing this time.

It worked for me

**Comment by dezu3** [comment]
Same problem in Windows Server 2012 R.
I have update Franz 4 for resolve this problem, but is worster in 5 beta

**Comment by g2chauhan** [comment]
I am facing the same problem.

Used Franz v5.0.0-beta.18 Release: 1.8.4 / Windows / x86
Operating System and version: Windows 10 and Ubuntu 18.0.4 (different machines)

**Comment by mikem33** [comment]
It's possible to solve it temporary to keep using the service but when you restart the app will fail again. To make it work, first I have opened the Developer tools and click on "Clear Storage" in "Application" tab. After that I have made a "hard" refresh of the window pressing cmd+shift+r (this is on mac, on Windows I suppose this is with ctrl+shift+r instead). After that you will have to scan again the QR code with your phone's Whatsapp app. That's all! I hope someone find a better way to solve it.

**Comment by tcelestino** [comment]
> It's possible to solve it temporary to keep using the service but when you restart the app will fail again. To make it work, first I have opened the Developer tools and click on "Clear Storage" in "Application" tab. After that I have made a "hard" refresh of the window pressing cmd+shift+r (this is on mac, on Windows I suppose this is with ctrl+shift+r instead). After that you will have to scan again the QR code with your phone's Whatsapp app. That's all! I hope someone find a better way to solve it.

Solved here!

**Comment by SergioSuarezDev** [comment]
same problem here

**Comment by g2chauhan** [comment]
> 
> 
> It's possible to solve it temporary to keep using the service but when you restart the app will fail again. To make it work, first I have opened the Developer tools and click on "Clear Storage" in "Application" tab. After that I have made a "hard" refresh of the window pressing cmd+shift+r (this is on mac, on Windows I suppose this is with ctrl+shift+r instead). After that you will have to scan again the QR code with your phone's Whatsapp app. That's all! I hope someone find a better way to solve it.

I restarted my windows system and used this quoted approach, and it works fine now. Thanks @mikem

**Comment by seguri** [comment]
@mikem33 I tried your solution but after cmd+shift+r I had to login again into Franz (thanks for not letting me paste the password!) and the same "WhatsApp works with Google Chrome 36+" window appeared.

**Comment by arlenn** [comment]
> It's possible to solve it temporary to keep using the service but when you restart the app will fail again. To make it work, first I have opened the Developer tools and click on "Clear Storage" in "Application" tab. After that I have made a "hard" refresh of the window pressing cmd+shift+r (this is on mac, on Windows I suppose this is with ctrl+shift+r instead). After that you will have to scan again the QR code with your phone's Whatsapp app. That's all! I hope someone find a better way to solve it.

Thank you @mikem33!
I had to use a combination of your approach above, and remove/re-add the service.
... but it is working now.

**Comment by henmedia** [comment]
I think Franz just sends a UserAgent that the WhatsApp Server doesn't accept as an actual browser ... I have the same issue with my v4 Franz. So there will be no permanent solution without an update of Franz ...

**Comment by globalcryptocoin** [comment]
MacOS with Mojave same issue, but after pressing cmd + shift + r it reloads and works

**Comment by zalaudekr** [comment]
MacOS 10.13.6 / Chrome Version 70.0.3538.110 (Offizieller Build) (64-Bit) not fixing with cmd+shift+r

**Comment by mikem33** [comment]
> MacOS 10.13.6 / Chrome Version 70.0.3538.110 (Offizieller Build) (64-Bit) not fixing with cmd+shift+r

Maybe, removing and adding the service will work. It's weird but for some people my approach work and for other people don't. Even I found myself today removing and adding the service because It does not work for me either.

**Comment by mikem33** [comment]
> > It's possible to solve it temporary to keep using the service but when you restart the app will fail again. To make it work, first I have opened the Developer tools and click on "Clear Storage" in "Application" tab. After that I have made a "hard" refresh of the window pressing cmd+shift+r (this is on mac, on Windows I suppose this is with ctrl+shift+r instead). After that you will have to scan again the QR code with your phone's Whatsapp app. That's all! I hope someone find a better way to solve it.
> 
> Thank you @mikem33!
> I had to use a combination of your approach above, and remove/re-add the service.
> 
> ** UPDATE **
> _SNAP_, reverts after restarting Franz.... not a solution :(

I know. I'm sorry but I already said it was a temporary solution...

**Comment by trinaldi** [comment]
Arch Linux also with the same problem.

**uname -a:**
`Linux trinaldi-linux 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux`

**Comment by marcosimonegili** [comment]
+1 on MacOS Mojave 10.14 (18A391)

**Comment by klouisbrother** [comment]
+1 on MacOS and Windows 10.

**Comment by arlenn** [comment]
There was a pop-up about services being updated a little while ago.  

I Re:Re'ed Whatsapp and restart Franz seems to have taken care of problems for me.... Can anybody confirm?

**Comment by aflatto** [comment]
Same problem on Ubuntu Bionic with installed Chrome [Version 70.0.3538.110 (Official Build) (64-bit)], and Franz 5.0.0-beta, removing and adding the service + restarting Franz , did not work.

**Comment by marcoguastalli** [comment]
Same issue with MacOS High Sierra and Franz Version 5.0.0-beta.18 (5.0.0-beta.18.903):

WhatsApp works with Google Chrome 36+
To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.

I updated Chrome, Firefox, removed the WhatsApp service and added again, no way.

**Comment by arditti** [comment]
+1
all the above suggestion didn't stick
Version 5.0.0-beta.18 (5.0.0-beta.18.903) osx 10.14

**Comment by ziloth** [comment]
I still have this issue. Franz 5.0.0-beta.19      Windows 10    17763.167
Temporary works method "Clear storage". After restart - again, "Clear storage", restart - ......

**Comment by krheinwald** [comment]
Problem still persists with Franz 5.0.0-beta.19 Windows 10

**Comment by macaubas** [comment]
Problem still persists with Franz 5.0.0-beta19 MacOS 10.14.1 Mojave
Temporary fix as described works, but just until next restart.

**Comment by Dudematters** [comment]
Not working on MacOS Mojave and latest Franz Beta update ... :( 

<img width="929" alt="screenshot 2018-12-03 at 08 39 27" src="https://user-images.githubusercontent.com/40238967/49360149-99e39d80-f6d8-11e8-839f-d6e8b19f13f9.png">
<img width="1146" alt="screenshot 2018-12-03 at 08 37 52" src="https://user-images.githubusercontent.com/40238967/49360160-a10aab80-f6d8-11e8-9d01-832c7cbe5b7a.png">

**Comment by Dudematters** [comment]
> Not working on MacOS Mojave and latest Franz Beta update ... :(
> 
Fixed it on MacOS Mojave by deleting all the preferences and Franz application support files.
Now it's working again.

**Comment by FKSI** [comment]
It worked after deleting *only*  Whatsapp service and adding it back. More convenient. Cool job for the dark mode!

**Comment by cenkingunlugu** [comment]
For me, only pressing `CMD + Shift +R` made it work. Fyi.

**Comment by WanaGo** [comment]
Deleting the Service and adding it back, makes it work.... until you restart and then its dead again.

**Comment by hknoener** [comment]
> I had the same issue this morning on
> Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / Windows / x64
> Operating System and version: Windows 10 - 1803
> However, I deleted all my services and added them again.
> Now it seems to be working for me again.

Same here. Removed Whatsapp service and added again, it's working now.

**Comment by hknoener** [comment]
> I had the same issue this morning on
> Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / Windows / x64
> Operating System and version: Windows 10 - 1803
> 
> However, I deleted all my services and added them again.
> Now it seems to be working for me again.
> 
> UPDATE: Restarted Franz. WhatsApp broken again and removing services does nothing this time.

Same problem here. Removed service -> Added service again -> worked -> restart franz -> Broken again.

**Comment by akratzel** [comment]
Works after re-adding the service. Stops working after relaunching Franz. 👎

**Comment by krheinwald** [comment]
WhatsApp broken on 5.0.0-beta.18 to 5.0.0-beta.19 on Windows 10 x64.
Updated from 5.0.0-beta.18 to 5.0.0-beta.19 on Windows 10 x64: No change
Removed WhatsApp service, added service again: works!
Restarted Franz: still works!

**Comment by macx** [comment]
🔴 Could you all please STOP posting the same problems and fixes again and again?

The problem is known, we don't have a software update to fix this issue at the moment. But there are temporary fixes above to use WhatsApp in the latest beta versions to help yourself.

**Comment by normeno** [comment]
> I had the same issue this morning on
> Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / Windows / x64
> Operating System and version: Windows 10 - 1803
> 
> However, I deleted all my services and added them again.
> Now it seems to be working for me again.
> 
> UPDATE: Restarted Franz. WhatsApp broken again and removing services does nothing this time.

It's works for me

**Comment by zerkc** [comment]
@macx  only you change the useragent 
https://stackoverflow.com/a/53366217

**Comment by zerkc** [comment]
this is a solution
```
mainwin.webContents.setUserAgent(mainwin.webContents.getUserAgent().replace(/(Electron|<nameyourapp>)\/([0-9\.]+)\ /,""));
```
paste in before loadURL;

**Comment by Sbatushe** [comment]
Same problem on Kali linux with last franz release.
version:
Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.13-1kali2 (2017-03-07) x86_64 GNU/Linux

**Comment by adlk** [comment]
This issue should be fixed for now! Please check for updates (Settings -> Settings -> Check for updates) or restart the app to get the updated WhatsApp recipe.

**Comment by pcmoreno** [comment]
For some reason, it was not fixing the issue with me until I "force quit" Franz. Then it went back to working fine again. (mac here)

**Comment by thisisablock** [comment]
@adlk 

still not working on beta 19. After Restart (also kill via shell) i still have this issue.

But, i found an hotfix for that issues:

Do not use Whatsapp as initial/first service.
I moved another service as initial/first service and now Whatsapp is loading correctly.

**Comment by adlk** [comment]
@edubkn please upgrade to Franz 5 via meetfranz.com

**Comment by SimStm** [comment]
Actually I just cleared the Franz v5 cache and solved my issue.

**Comment by Mayccoll** [comment]
On Linux Mint - Work for me
- Electron Version 4+
```
Menu > Edit > Clear App Data
```

**Comment by bartoszek** [comment]
Not working here `Arch linux, franz 5.0.0_beta.18-1` I've been clearing and restarting times again without result
![zrzut ekranu z 2018-12-13 10-21-02](https://user-images.githubusercontent.com/1213348/49928631-d7a6aa00-fec0-11e8-9a4a-a0a40bf466b7.png)
.

**Comment by FilipaSimao** [comment]
Same problem here

**Comment by adlk** [comment]
This issue is an issue with WhatsApp, **not Franz**. I'm however trying to find a proper work around for their issues but at this point there is not much I can do.

I'm going to lock this issue!
