### ISSUE TITLE
Unable to zoom in/out in any service

### ISSUE THREAD

**Issue by markwalkom** [meetfranz/franz#1289]
**Describe the bug**
Unable to zoom in or out on any service that has been installed.

**To Reproduce**
1. Open the app
2. Try to zoom in/out using key shortcuts
3. Try to zoom in/out using the View menu options
4. Nothing happens

**Expected behavior**
Window size changes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS, 10.14.3 (18D42)
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
This is a fresh install of Version 5.0.0 (5.0.0.1136).

**Comment by zombiespawn** [comment]
+1 I would also like zoom as a feature on the services, only one that works is what's app

**Comment by MaTriXy** [comment]
The issue is that only one service will get the zoom commands , if you have more than one service enabled. 
If you will do zoom in/out in one of the services and navigate to other services you will see that the zoom of one of them has changed and the others are intact. 
The fix should try to apply the zoom on the currently active service and not on the others ( i assume)

**Comment by adimasuhid** [comment]
+1 Just recently happened. Previous version zoom ins were working well.

**Comment by mliq** [comment]
On Franz 5.1.0, US keyboard, Macbook Pro latest, macOS 10.14.4 (latest): 

Zoom is working well and on a per-app basis. 

_The only quirk is_ that I must use <kbd>cmd</kbd>+<kbd>**_shift_**</kbd>+<kbd>=</kbd> to zoom in. This kind of makes sense considering that you need <kbd>shift</kbd> to access <kbd>+</kbd>, but no other app requires this.

**Comment by JoseConstanza** [comment]
+1 On Windows happend too.

**Comment by alexdevero** [comment]
Zooming in/out doesn't work in 5.2.0-beta.2 on Windows 10.

**Comment by YoguiSnow** [comment]
Update 5.2.0-beta.3, work again.

**Comment by bittner** [comment]
Would it make sense to change the keyboard shortcut back to <kbd>Ctrl</kbd>+<kbd>+</kbd> for zooming in? I believe it was like that earlier.

**Comment by SergeyG488** [comment]
Can't zoom in on franz app. Keyboard shortcuts or menus do not work. Version franz 5.4.1 . Reinstalled the application with the removal of information from the user profile. Nothing has changed. Win10 Version 1903 (OS build 18362.476). What else can be done? The font is very small. I would like to increase.

**Comment by zombiespawn** [comment]
5.3.3 works. Just roll back for now.

**Comment by jefferson-lima** [comment]
I'm having the same problem with version 5.4.1 on a Arch Linux fresh install.

**Comment by denisvidal** [comment]
same problem on version 5.4.1.1703 on macOS Catalina

**Comment by fsauceda** [comment]
I have the same problem on 5.4.1 on Windows 10

**Comment by bittner** [comment]
This issue is already fixed (via PR #1668).

**Comment by alexdevero** [comment]
This issue is not fixed because zooming in/out/actual doesn't work in v5.4.1 (Windows 10).

**Comment by bittner** [comment]
This issue is fixed for version 5.5.0 (that's visible from the PR). @adlk merged the fix into branch  `meetfranz:release/5.5.0`. You need to wait for the v5.5.0 release now.
