### ISSUE TITLE
Your services have been updated message persists.

### ISSUE THREAD

**Issue by ccioanca** [meetfranz/franz#1453]
The "Your services have been updated." message keeps popping up regardless of if I reload the service or not. This has been happening for a few weeks now, and have just been deleting it via dev tools. I decided to report in case others are experiencing the same thing. 

See below for screenshot:

![image](https://user-images.githubusercontent.com/13683999/58426968-307f8e80-806c-11e9-9e9b-50c599acbf78.png)

 - OS: Windows 10
 - Browser: Chrome 
 - Version: V 5.1.0

If this is not an issue that's happening to anyone else, then I will delete this.

**Comment by suenchunhui** [comment]
same to me, I had been having this problem across multiple versions of Franz.

franz: 5.1.0
OS: ubuntu 18.04

**Comment by cmccandless** [comment]
I've been experiencing this since 4.5-something.

Version 5.2.1-beta.1
OS: Ubuntu 18.04

**Comment by ccioanca** [comment]
This has been fixed in the latest version:

Version: 5.3.0 (2019-09-06)

**Comment by cmccandless** [comment]
Not resolved. Also, now Teams won't work because cookies have been disabled?

![image](https://user-images.githubusercontent.com/7275238/64614792-46108e00-d3a7-11e9-8168-db007e192fc3.png)

**Comment by ccioanca** [comment]
Hmm. I also use Teams. And it has been working fine for me. Have you tried copying your recipes and just doing a clean install? That might help. If it doesn't, I will reopen the issue to be reviewed.

**Comment by cmccandless** [comment]
@ccioanca What is the best way to perform a clean install on Linux?

**Comment by ccioanca** [comment]
@cmccandless I think that `sudo apt-get --purge remove` will do the trick. I have no idea if it leaves behind configs or empty folders. But I would assume it doesn't. Give that a go.

**Comment by cmccandless** [comment]
A clean install seems to have resolved my issue.
