### ISSUE TITLE
No What's app notification icon on the Franz logo

### ISSUE THREAD

**Issue by ghost** [meetfranz/franz#1459]
**Describe the bug**
Recently when I use the What's app service, the red notification icon won't show up anymore when i receive a message. So i can't see if i got something new or not. Anyone knows how to fix this?

**Expected behavior**
Get a red notification icon on the What's app and Franz logo.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise, version 1803, build 17134.765
- Franz: 5.1.0

**Comment by brhahlen** [comment]
Seeing the same behaviour.
Windows 10 1903
Franz 5.1.0

**Comment by nirusuu** [comment]
same here

**Comment by JDoe0000** [comment]
Same thing happening on MacOS!

**Comment by JCKodel** [comment]
Same, Windows 10 1903, Franz 5.1.0

**Comment by LurchiStromberg** [comment]
Same here, Win 10 64 Bit.
There been same issue some Months ago.....
A Fix would be cool...

**Comment by Dareiko** [comment]
Same after update to 1903 version of Windows 10.

**Comment by msamec** [comment]
I believe this was fixed. I just received a notification to reload the app, once I did this started working for me again.

**Comment by MrNicker9** [comment]
It seems like it is indeed fixed! For me it is working again and i did not change anything.
Franz version: 5.1.0
Release: 4.1.4 / win32 / x64

**Comment by brhahlen** [comment]
Is not yet fixed for me, have restarted the app a few times, got the "Reload" message as well, but so far, no WA notification.

**Comment by Dareiko** [comment]
I have two account, one is working and one not. Strange.

**Comment by mpaezt** [comment]
deployed in different servers I suppose!
