### ISSUE TITLE
Slack notifications are not working

### ISSUE THREAD

**Issue by deepak365** [meetfranz/franz#1545]
**Describe the bug**
I am not getting slack notifications. 

**To Reproduce**
1. Add slack as a service
2. You will see no notifications for a new message on slack.

**Expected behavior**
Notifications should come for a new message.

**Desktop:**
 Franz: Version 5.2.0 (5.2.0.1455)
OS: macOS 10.14.5 (18F132)
Laptop: MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports) 

Is anyone else facing this issue?

**Comment by willbeeching** [comment]
Having the exact same problem. All other services seem to serve notifications except Slack.

**Comment by chicojasl** [comment]
Same here.

**Comment by vlinas** [comment]
Same

**Comment by mhadidg** [comment]
I have the same problem. Linux user (Ubuntu 19.04) here using latest version of Franz: 5.2.0

**Comment by hos4m** [comment]
Same issue
Franz 5.2.0
MacOS Mojave 10.14.6

**Comment by sakekasi** [comment]
Same here:
Franz 5.2.0.1455
MacOS 10.14.5

**Comment by LainaRaquel** [comment]
I have this issue but with Discord. I don't use slack. It's very frustrating so I feel you. 
I have the latest update or franz and windows 10.

**Comment by deepak365** [comment]
Update: Issue is fixed in this beta `v5.2.1-beta.1`. I have tested.  

![image](https://user-images.githubusercontent.com/2122305/62177392-64c04580-b362-11e9-9168-b9b1ceb880ba.png)

Commit: https://github.com/meetfranz/franz/commit/44c413b
Release: https://github.com/meetfranz/franz/releases/tag/v5.2.1-beta.1

Thanks @adlk .

**Comment by mhadidg** [comment]
The problem is back!
Two weeks ago, I upgraded to v5.2.1-beta.1, and it fixes the issue. However, I am experiencing the same problem today. 

Can anyone please confirm (or disconfirm) that?

**Comment by imOscarCrespo** [comment]
i've the same problem!!

**Comment by derdaani** [comment]
5.3.3 notifications from Slack not working :(

**Comment by teu** [comment]
Notifications not working again. 
macos catalina, franz 5.5.0 (5.5.0.1762)

**Comment by FallOutChonny** [comment]
> Notifications not working again.
> macos catalina, franz 5.5.0 (5.5.0.1762)

+1
os version: 10.15.5
franz version: 5.3.3

**Comment by rizqiimani** [comment]
> Notifications not working again.
> macos catalina, franz 5.5.0 (5.5.0.1762)

+1 Franz 5.5.0, MacOS 10.15.6
