### ISSUE TITLE
Franz suddenly stuck on initial loading screen for very long.

### ISSUE THREAD

**Issue by Twisterking** [meetfranz/franz#1689]
**Describe the bug**
After a normal restart of my Mac I can't start Franz again. The app is completely stuck on the blue loading screen. Deleting, downloading and installing current version did not help!

**To Reproduce**
1. Well ... can't start! ;)
2. after many minutes it might "start" - then it says "Couldn't load service and Userinformations in the bottom red bar"

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Version: 5.4.1

**Comment by JiSiN3000** [comment]
Exact same behavior here on Windows 10 Pro (1903)
Version: 5.4.0-beta.3
Everything was fine until yesterday (11.11.2019)

**Comment by awunder** [comment]
proly a server down..

however, that begs the question why the services are not stored offline for backup...(?)

**Comment by Head** [comment]
https://meetfranz.com/de/services looks like a server issue...

**Comment by DarwinOnLine** [comment]
Same here, unable to load any service...

**Comment by DickonForKing** [comment]
> Exact same behavior here on Windows 10 Pro (1903)
> Version: 5.4.0-beta.3
> Everything was fine until yesterday (11.11.2019)

Same issue here

**Comment by DarthSonic** [comment]
Problem also on stable 5.3.3

**Comment by elyday** [comment]
Same problem on Linux Mint 19.2 Cinnamon

**Comment by jurgenhaas** [comment]
Same here on Linux with version 5.4.0 - the problem seems to be the login service, because even the login on https://meetfranz.com/login in a web browser doesn't work.

**Comment by pix-art** [comment]
Fixed :-)

**Comment by jm96441n** [comment]
I'm still having this issue on mojave. Previously franz would would become unresponsive every once on launch, now every time I go to launch it instantly becomes unresponsive or just crashes.

**Comment by mimavox** [comment]
Still an issue on Linux Cinnamon :(

**Comment by Lod3** [comment]
Same here ubuntu 18
