### ISSUE TITLE
Links open empty chrome tab

### ISSUE THREAD

**Issue by dingledong** [meetfranz/franz#264]
### Current Behavior

when clicking any link, they are not opened (has been like this for a week maybe): a web browser is opened, but is not redirecting to the link that was clicked. 
(i've tried it in slack, whatsapp and outlook, doesnt work in any of them)

**Comment by adlk** [comment]
A similar issue has already been reported at the community slack. Have you restarted Franz in the meantime?

**Comment by dingledong** [comment]
yes, several times, and updated it. did not help

**Comment by adlk** [comment]
Ok, thanks!
Can you please update your initial post with the missing information from the issue template? Otherwise it's impossible for me to keep track of it.
https://raw.githubusercontent.com/meetfranz/franz/master/.github/ISSUE_TEMPLATE.md

**Comment by Mastergalen** [comment]
Same problem for me started happening today.

Tried restarting, reloading Franz, but the problem persists.

### Expected Behavior
Click on a link inside a client e.g. Messenger or  Google Inbox and it should open a new tab with that link in my default browser (Chrome).

### Current Behavior
Clicking the link opens a whole new Chrome window with a new tab that is blank `about:blank`

### Steps to Reproduce (for bugs)
Click on a link inside Messenger or Google Inbox. Haven't tested other services.

### Your Environment

* Franz Version used: Version 5.0.0-beta.13 (5.0.0-beta.13.316)
* Operating System and version: Mac OS High Sierra 10.13.1
* Chrome: Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by Mastergalen** [comment]
Fixed after updating Chrome to `Version 62.0.3202.94 (Official Build) (64-bit)`

**Comment by gabrielalan** [comment]
@Mastergalen I'm using a higher version chrome, but it's not working.

- Franz Version used: Version 5.0.0-beta.14
- Operating System and version: Mac OS High Sierra 10.13.1
- Chrome: Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by adlk** [comment]
This actually seems to be an issue with Chrome. A Chrome restart usually helps.

**Comment by alexmilk** [comment]
@adlk What you mean by Chrome restart? Closing the application and reopening again did not improve anything.

**Comment by gabrielalan** [comment]
@alexmilk same here.

**Comment by ynotLeft** [comment]
Issue persists with exactly Chrome Version 62.0.3202.94

**Comment by gb-jlofton** [comment]
For anyone still looking at this, just type (chrome://restart) into your chrome browser and it should fix the problem.

**Comment by mturley** [comment]
For any future internet searchers who find this, I had this issue in many other applications (not in franz) and found this thread when I was troubleshooting. chrome://restart worked for me! Before that, I wasn't able to open links from ANY external app (At first I thought it was Electron apps, since the problem was in Atom plugins, Slack, Discord, Boxy, etc... then I noticed it was happening in Outlook too). They would all open an empty tab.

**Comment by arun02139** [comment]
chrome://restart worked for me as well!!

**Comment by haraldox** [comment]
@BrianGilbert's workaround: right-click and select "Open Link"

**Comment by amouratoglou** [comment]
same happens in Ubuntu 17 ,  Chrome version (64.0.3282.167-1).

**Comment by dmeza** [comment]
For anyone still looking. It is a Chromium issue and the solution seems to be coming with Chromium 65 in beta right now. The the thread of the issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=777863#c18

**Comment by trentrand** [comment]
Issue fixed with newest release of Chrome (64.0.3282.186)

**Comment by funfried** [comment]
Yesterday I was having this issue (again) with Chrome 64.0.3282.186 on macOS High Sierra, it seems it's still not fixed :(

**Comment by alexmilk** [comment]
@funfried The best solution for this right now is to close and reopen the browser.

**Comment by kevindavis** [comment]
This has happened intermittently for me for some months now (macOS). Restarting Chrome always fixes it. 

Possible this is happening when a new version of chrome is downloaded but you need to restart to install it? Having finally googled this, I saw this thread and checked my version number. It was 64.x.x.x or whatever, but a new version had downloaded.

**Comment by knitterb** [comment]
Version 64.0.3282.167 (Official Build) (64-bit)

This issue is still occurring.  Restarting does resolve this, but that solution is a less than optimal one.

**Comment by RavBhagdev** [comment]
This has been happening for over a week (mostly mac users).  My version is 3.1.0-beta1 PR4132/2f99420 (Beta)

There are >2 dozen people using mac on team, all with same.

**Comment by benurb** [comment]
This is fixed with Chrome 64.0.3282.186

**Comment by knitterb** [comment]
See @funfried 's comment.  This doesn't appear to be fixed on ...186.  I just updated and I'll see if it helps, but this isn't something that happens all the time.  It appears to creep in after a good number of days of Chrome running.  It's really hard to repro, but once it starts happening, it always occurs.

**Comment by meteorplus** [comment]
it's chrome sleeping just get it a good blanket and never worry again :D

**Comment by howardjones** [comment]
Same issue with Chrome 65.0.3325.146 and links in Thunderbird 52.6 or Terminal. On Ubuntu 16.04 LTS 64-bit. I previously had Chromium (which worked fine), installed Chrome and used Chrome's own UI to set it as the default browser.

I get it all the time. Restarting Chrome doesn't help.

**Comment by akmal** [comment]
Version 65.0.3325.181 

Still has this problem.

**Comment by musfars** [comment]
Facing the same issue for links from slack.
Chrome version: 66.0.3359.139
`chrome://restart` doesn't help.

**Comment by rabiamarzhiya** [comment]
Version 67.0.3396.62 (Official Build) unknown (64-bit) ( ubuntu 16.04)
Still has this problem. Restarting makes no difference

**Comment by erichahn** [comment]
Also facing this issue. Version 67.0.3396.79 (Official Build) unknown (64-bit)

**Comment by 7091lapS** [comment]
Still happening with links in hangouts chat, chrome v 67.0.3396.87. Chrome restart makes no difference.

**Comment by UnityGio** [comment]
I'm seeing this with Slack on Chrome  67.0.3396.87 (Official Build) (64-bit)

**Comment by vk-sourcefuse** [comment]
'm seeing this with Slack on Chrome 67.0.3396.87 (Official Build) (64-bit)

**Comment by vk-sourcefuse** [comment]
This simple solution worked for in https://askubuntu.com/questions/820900/slack-fails-to-open-links-in-ubuntu-14-04

**Comment by meteorplus** [comment]
link is not working

**Comment by vk-sourcefuse** [comment]
Did u tried solution told there :
https://askubuntu.com/questions/820900/slack-fails-to-open-links-in-ubuntu-14-04

It's working in all VERSIONS OF UBUNTU

**Comment by erichahn** [comment]
@vk-sourcefuse solution worked for me! Not sure why most updated version did not include that in the .desktop launch file

**Comment by rjw245** [comment]
@vk-sourcefuse Thanks for the fix! That worked for me.

**Comment by UnityGio** [comment]
What about for Windows?

**Comment by atanaschristov** [comment]
Ubuntu: 16.04
Chorme: Version 68.0.3440.106 (Official Build) unknown (64-bit)
I had the same issue until  @vk-sourcefuse brought me on the right track. Thanks.

**Comment by abdelhalimresu** [comment]
For those who still have this issue even after `chrome://restart` . 
Edit the file `$HOME/.local/share/applications/google-chrome.desktop` by replacing:
`Exec=/opt/google/chrome/chrome`
with:
`Exec=/opt/google/chrome/chrome %U`
this worked for me.

**Comment by DivyaPrajapati09** [comment]
i was also having the same problem after lot of searching used the answer of @vk-sourcefuse partially and resolved it. 
Google-chrome version : **Version 70.0.3538.110 (Official Build) unknown (64-bit)**
Os : **Ubuntu**
First look for the file google-chrome.desktop in given path : $HOME/.local/share/applications/google-chrome.desktop
After you find the file, right click on it and select the properties. In properties, select the permission tab and check the checkbox for Allow executing as a program and click ok. This will change the icon of the file to chrome logo. And now you can launch and check whether it is opening the links or not.
Hope it helps
