### ISSUE TITLE
Links Open New Blank Tab

### ISSUE THREAD

**Issue by jflan1** [meetfranz/franz#272]
### Expected Behavior
Links should open when shared in services used on Franz (WhatsApp, Skype, Slack)

### Current Behavior
Clicking on links opens in new blank window, rather than opening the expected link.

### Your Environment
* Franz Version used: 4.0.4
* High Sierra

**Comment by adlk** [comment]
Franz 4 is no longer maintained, please upgrade to Franz 5 (www.meetfranz.com/#download)

**Comment by jflan1** [comment]
Thanks for this suggestion.

I installed five, I was able to log in to most of my accounts apart from Slack. I get the "You've Found a Glitch" window, with no option to log-in. 

When I click log-in on the menu in the slack window, it opens a new blank tab in Chrome (which was my original issue). I am currently logged in to Slack on both Chrome and the Slack app itself, so I know for sure there is no issue with my Slack account.

**Comment by adlk** [comment]
This usually happens when your slack team isn't correct. Can you provide me with the Team Id you have entered in in Franz?

**Comment by jflan1** [comment]
Thanks, I managed to get it sorted!

**Comment by drorata** [comment]
I have this same problem (blank web pages opened when clicking on links inside Franz) using Franz 5.0.0-beta 13.316.

**Comment by adlk** [comment]
@drorata this is an issue with chrome. You need to restart and everything should be working again. More information can be found here #264

**Comment by tnrich** [comment]
I'm still seeing this in the latest version of franz Version 5.0.1 (5.0.1.1237)

![franz](https://user-images.githubusercontent.com/2730609/54959603-e583b680-4f16-11e9-926b-d16970a2bb39.gif)

**Comment by tnrich** [comment]
@adlk  typing `chrome://restart` into my chrome browser doesn't seem to help in my case. still definitely seeing this issue..
